username: cisco
password: cisco

# Network Devices

devices:
  - name: spoke1
    host_ip: '127.0.0.1'
    netconf_port: 
    VRFs:
      - name: RED
    Profiles:
      - name: vpnprof
    interfaces:
      - name: GigabitEthernet2
        enabled: "true"
        ip: '10.10.10.2'
        mask: '255.255.255.0'
    TunnelInterfaces:
      - name: 0
        enabled: "true"
        ip: '10.0.0.2'
        mask: '255.255.255.0'
        source: GigabitEthernet2
        profile: vpnprof
        nbma_ip: '10.10.10.1'
        hub_ip: '10.0.0.1'
        VRF: RED
        key: 100000
        network_id: 100000
    ospf:
      process_id: 1
      networks:
       - network: 10.10.10.0
         wildcard: 0.0.0.255
         area: "0"